### ISSUE TITLE
Linter crashing

### ISSUE THREAD

**Issue by macMikey** [trevordevore/sublimelinter-contrib-livecodelint#2]
Is anyone else having an issue with the ST linter crashing when opening LCS files?  I'm using SL4 with ST3 3.1.1 build 3176

SublimeLinter: #1 livecodelint u.livecodescript ERROR:
======================================================

Linter crashed.

Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1147, in _communicate
    creationflags=util.get_creationflags()
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1370, in _execute_child
  File "./python3.3/os.py", line 791, in fsencode
TypeError: expect bytes or str, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 87, in execute_lint_task
    errors = linter.lint(code, view_has_changed, settings) or []
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 748, in lint
    output = self.run(None, code)     # type: str
  File "/Users/me/Library/Application Support/Sublime Text 3/Packages/sublimelinter-contrib-livecodelint/linter.py", line 61, in run
    return self.communicate(cmd, code)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1066, in communicate
    return self._communicate(cmd, code)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1153, in _communicate
    cmd, uses_stdin, cwd, view, augmented_env))
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package/lint/linter.py", line 1257, in make_nice_log_message
    cmd=' '.join(cmd)
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by trevordevore** [comment]
I'm not. SL 4 required some configuration setting changes I believe. What does your Sublime Text > Preferences > Package Settings > Sublime Linter > Settings User file look like? Here is mine:

```
// SublimeLinter Settings - User
{
  "show_panel_on_save": "view",
  "linters": {
    "livecodelint": {
      "disable": false,
      "args": [],
      "excludes": [],
      "explicitvars": true,
      "livecode-server-path": "/usr/local/bin/livecode-community-server"
    }
  }
}
```

**Comment by macMikey** [comment]
Making sure I did this correctly:
I got at the file by hitting command-shift-p
typing "preferences:sublime linter"
My file was blank.
I copied/pasted yours
that fixed it.

**Comment by trevordevore** [comment]
Very good.
